In [1]:
import numpy as np
# generate 3 random numbers
np.random.rand(3)

array([ 0.41642488,  0.73672378,  0.89486297])

In [3]:
# N dimensional numpy arrays
earnings = [
    [
        [500, 505, 490],
        [810, 450, 678],
        [234, 897, 430],
        [560, 1023, 640]
    ],
    [
        [600, 605, 490],
        [345, 900, 1000],
        [780, 730, 710],
        [670, 540, 324]
    ]
]
earnings = np.array(earnings)
earnings[0, 0, 0]

500

In [4]:
earnings.shape

(2, 4, 3)

In [5]:
earnings[:, 0, 0]

array([500, 600])

In [6]:
earnings[:, 0, :]

array([[500, 505, 490],
       [600, 605, 490]])